### ISSUE TITLE
cyNotifyer - Crash on 3.3.2 x64

### ISSUE THREAD

**Issue by Tha14** [cydolo/cyPlugins#1]
Hey, cyNotifyer crashes my TS3 client on startup. Crash Dump attached bellow.
Cheers
[ts3dump_1572714006054.zip](https://github.com/cydolo/cyPlugins/files/3800749/ts3dump_1572714006054.zip)

**Comment by cydolo** [comment]
does the crash happens if you open the gui?

I can not see in the crashdump that this is the cynotifyer plugin so maybe you move all other plugins out of the plugin folder and try it again.

the plugins are also all outdated because the api needs to be rechanged.

**Comment by Tha14** [comment]
All of the plugins are up to day. I also tried with a clean TS3Client folder on appdata and just the cyNotifier and it still crashed the same way. I can post a crashdump again if you want.

**Comment by cydolo** [comment]
Try to move all plugins out of the plugin folder and only use the cynotifyer should it crash again send me the crashdump of it.

**Comment by Tha14** [comment]
I completely reinstalled all vcredist versions and it started working now.
